[tool.black]
line-length = 88
target-version = ["py312"]
skip-string-normalization = false

[tool.mypy]
python_version = 3.12
ignore_missing_imports = true
strict_optional = true
check_untyped_defs = true
disallow_untyped_defs = true
show_error_codes = true
plugins = ["mypy_django_plugin.main"]


[tool.django-stubs]
django_settings_module = "my_portfolio.settings"





