# Generated by Django 4.2.3 on 2023-07-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="arrticle",
            field=models.TextField(default=""),
        ),
    ]
