# Generated by Django 4.2.3 on 2023-08-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_arrticle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=256)),
                ("link", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
