# Generated by Django 4.2.3 on 2023-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_suggest_blog_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
    ]
