# Generated by Django 4.2.4 on 2024-02-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_portfolio_is_it"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(default="What I used:\nDescription:"),
        ),
    ]
