# Generated by Django 4.2.4 on 2024-02-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_portfolio_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="is_link",
            field=models.BooleanField(default=False),
        ),
    ]
